version: '3.8'

volumes:
  postgres_data: {}

services:
  frontend:
    build: ./frontend
    tty: true
    volumes:
      - type: bind
        source: ./frontend
        target: /frontend
    ports:
      - 8080:8080
    depends_on:
      - backend

  backend:
    build: ./backend
    tty: true
    volumes:
      - type: bind
        source: ./backend
        target: /backend
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:13.3
    environment:
      POSTGRES_PASSWORD: postgres_password
    volumes:
      - type: volume
        source: postgres_data
        target: /var/lib/postgresql/data
